image:
  repository: ghcr.io/mribrgr/not-just-a-developer.com
  tag: "v0.10.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: mauritiusberger-de
            servicePort: 80
    - host: grocy.mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: grocy
            servicePort: 80
    - host: ghostfolio.mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: ghostfolio
            servicePort: 3333
    - host: n8n.mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: n8n
            servicePort: 5678
    - host: obsidian.mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: obsidian
            servicePort: 3000
  tls:
    - secretName: mauritiusberger-de-tls
      hosts:
        - mauritiusberger.de
    - secretName: grocy-mauritiusberger-de-tls
      hosts:
        - grocy.mauritiusberger.de
    - secretName: obsidian-mauritiusberger-de-tls
      hosts:
        - obsidian.mauritiusberger.de
    - secretName: ghostfolio-mauritiusberger-de-tls
      hosts:
        - ghostfolio.mauritiusberger.de
    - secretName: n8n-mauritiusberger-de-tls
      hosts:
        - n8n.mauritiusberger.de

