image:
  repository: ghcr.io/mribrgr/not-just-a-developer.com
  tag: "v0.6.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: not-just-a-developer.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: not-just-a-developer-com
            servicePort: 80
    - host: grocy.not-just-a-developer.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: grocy
            servicePort: 80
    - host: ghostfolio.not-just-a-developer.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: ghostfolio
            servicePort: 3333
  tls:
    - secretName: not-just-a-developer-com-tls
      hosts:
        - not-just-a-developer.com
    - secretName: grocy-not-just-a-developer-com-tls
      hosts:
        - grocy.not-just-a-developer.com
    - secretName: ghostfolio-not-just-a-developer-com-tls
      hosts:
        - ghostfolio.not-just-a-developer.com

