image:
  repository: ghcr.io/mribrgr/not-just-a-developer.com
  tag: "v0.11.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

velero:
  initContainers:
    - name: velero-plugin-for-microsoft-azure
      image: velero/velero-plugin-for-microsoft-azure:v1.10.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  
  configuration:
    provider: azure
    backupStorageLocation:
    - name: default
      provider: azure
      bucket: netcup
      config:
        storageAccount: azureresticbackup
        storageAccountKeyEnvVar: AZURE_ACCOUNT_SAS

  credentials:
    useSecret: true
    existingSecret: velero-credentials

  deployNodeAgent: true

  nodeAgent:
    podVolumePath: /var/lib/kubelet/pods

  schedules:
    daily-backup:
      disabled: false
      schedule: "0 2 * * *"
      template:
        ttl: "720h"
        defaultVolumesToFsBackup: true

  hosts:
    - host: mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: mauritiusberger-de
            servicePort: 80
    - host: grocy.mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: grocy
            servicePort: 80
    - host: ghostfolio.mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: ghostfolio
            servicePort: 3333
    - host: n8n.mauritiusberger.de
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: n8n
            servicePort: 5678
  tls:
    - secretName: mauritiusberger-de-tls
      hosts:
        - mauritiusberger.de
    - secretName: grocy-mauritiusberger-de-tls
      hosts:
        - grocy.mauritiusberger.de
    - secretName: ghostfolio-mauritiusberger-de-tls
      hosts:
        - ghostfolio.mauritiusberger.de
    - secretName: n8n-mauritiusberger-de-tls
      hosts:
        - n8n.mauritiusberger.de

