# The URL the site will be built for
base_url = "http://not-just-a-developer.com"
# base_url = "http://localhost"

compile_sass = false

build_search_index = false

theme = "radion"
taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "visual-studio-dark"

[search]
index_format = "elasticlunr_json"

[extra]
radion_menu = [
    {url = "$BASE_URL", name = "Home"},
    # {url = "$BASE_URL/categories", name = "Categories"},
    # {url = "$BASE_URL/tags", name = "Tags"},
    # {url = "https://google.com", name = "Google"},
]

# Put all your custom variables here
favicon = false # TODO
github = "https://github.com/mribrgr"
# codeblock = true # (Clipboard Support and Language Tags)
# latex = true
enable_search = false
toc = true # page content
comments = false
# if I ever want to, also set:
# giscus_repo = "FILL ME IN"
# giscus_repo_id = "FILL ME IN"
# giscus_data_category_id = "FILL ME IN"
theme = false

