apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghostfolio
  template:
    metadata:
      labels:
        app: ghostfolio
    spec:
      initContainers:
        - name: check-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -zv postgres 5432; do echo "Waiting for db"; sleep 2; done;']
        - name: check-redis
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -zv redis 6379; do echo "Waiting for redis"; sleep 2; done;']
      containers:
        - name: ghostfolio
          image: ghostfolio/ghostfolio:latest
          env:
            - name: COMPOSE_PROJECT_NAME
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: COMPOSE_PROJECT_NAME
            - name: REDIS_HOST
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: REDIS_PASSWORD
            - name: POSTGRES_DB
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: POSTGRES_PASSWORD
            - name: ACCESS_TOKEN_SALT
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: ACCESS_TOKEN_SALT
            - name: DATABASE_URL
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:  
                secretKeyRef:
                  name: ghostfoliosecret
                  key: JWT_SECRET_KEY
          ports:
            - containerPort: 3333
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 10
            periodSeconds: 5