---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8nllmsecret
  namespace: default
spec:
  encryptedData:
    LITELLM_API_KEY: AgBRjXMI6FWS5IhT/AevpcTdiI8rP/tijsybs7rRg2fF1m/D++L2MpHJMW5tK/UhAreKDfYauXyRu0IBF0OtI/VlzV8VS/GdT3W3tsXx/pXL9v/9R08A1yxbFkP0L4m55SX6vhiVkh+8KI5XAa/PpwA01jE/cELhum4BPwJg58kYi5kKELH0Bz0bLHQon7A44XCdUn6GrZHt6x5If5lkGFE2yC79PE53J/GF/hMersIPFbSiZ5F45KjBH7rhTP/mNlTqBCAUWVh52hzRF9VmXD0DEsH0K7UfTEVkaEZ53f4tkydH0JuOyO/fGR1XE1xtmvTahiAtssV4Wv9PiGM8YyN76JEmDQ4l/tBnOQtqLsbM+ZDc5qtJA873NiPXDXC/IaGe/LcFgNsMLV+U55CrWINsZFyzNX4W8CZGKPMX0qSMt6SE6HeucT1RNw8RPx9aL/QqW7I/9hYp/UtNlb2CfZLaqpS9dc0osb2l/F/S3JrAR27KhENyNZLPa3nNGQdw3RLA0/sCHc0NCToVJ3kUG1F10bx6KeoG6DTBWpfYUeVwd6/niJpQvA29Ojb9TvPPvuXnj4Qg9LuNjEL7vAcvcke8fXu7RW6TQfzL82fUi6rAsNGU57k+a2X1h+tPYcmLN5STjc0wdqVy4iCm08h0AwYOfNvQ4CQNndWIAv8mLqPAe6J7/B3cBqwaZQGCRliYaRHFYRIPFwMYiNOIeouBtOHuxiqeXNlE9gd3
  template:
    metadata:
      name: n8nllmsecret
      namespace: default
