---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8nllmsecret
  namespace: default
spec:
  encryptedData:
    LITELLM_API_KEY: AgBOUAmsXeJn/UCXR/hw1aQOHsaIx0mzbeJrxpejswxT/KXQIWvnoOvfZhEZpJT4n9zjjK0Ckys5iAhXkCv2x3UOnrqpJi7o+mDOJE2z+uydYqclGcCxiVhFv5jtoIAGD4xzBYWsNKaH6Nq/PkELUumUkGXIF1bVXohq7THkgr9O7AoC/b5yFNSgqrEOHM6wi9dmLTcpLK9+DlnPeO4JEFDv252lzT5nRTOsqkgkIcIc0+QeT09hI2wJuP6NhyYIOkdj1/m2EUUIUDdtOuJEzC8WeRBS/Mhex5vTI2Apy3NkDVlua6aVGe/yS55ZbjOXTIWgBjI8QP6S7aU1qXYSI6Vyisg7xoYG6fOk6SFE6jwWLP+LB+7FjLeM8eCDL0gnSSLWB6Bk3tZOBUaUZahn4IbrJsp+z0FIVAvCFm3fHqpql9w/ysFPW+tYhL2DdtqAmJcXRfBfAj8iW7WJB8daARH9d/M+KTzd8xXXBgAnv9jov2UsjrrGz8lDE/0F5nAp6n8Bcg+0mLpCc0EfDyfGib7jdWF0Ij4I1ZcnxdDi8TUHp24/a3D0RysYOH8uWYz05gDyOgyvPJP7amzkVjVqShh9ICq79A3/Z4S0HFXdAj39iLkA4t8DrxS7bTY4DyPQX5q+U/7UJReYJ8e4hTbQNIM6Ja+QeVytarlHwwOAdQFarlICwWQiTtYa9OU79hipgXV6b3/P6AgTUm257htYQ01nxMDHpRSha34p
  template:
    metadata:
      name: n8nllmsecret
      namespace: default
