apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis:alpine
          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          envFrom:
            - secretRef:
                name: ghostfoliosecret
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --pass
                - "$(REDIS_PASSWORD)"
                - ping
            initialDelaySeconds: 20
            periodSeconds: 10
      resources:
        requests:
          ephemeral-storage: "256Mi"
        limits:
          ephemeral-storage: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379