---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: default
spec:
  encryptedData:
    cloud: AgBn3vhrAZCepU2QiEXoqayEsQ8/jOpqY2Hmtp8v69JqPZMLanXqewgqsXpwt0WGqEFRuwq9SW/31ybH+5bXsQ7u/E3wghVxImGgJ4QrzlstJLTE6SZlpWElioSlzlpAmDKeZyt3gzAUKuvWaGy8bMvXD2nA+ctjXZlPzfx9uw5vugoSCkkf4q+cNpcVPhwOyJrWwK/oiJ4OQZ7b/jcTdobG4je5JavXfKOssI8L6wOXRYWQv+utZj/YLbzxlnGWTVoZ03YFymzSTMmWoxKfZLepDf61O5URrBDkYOgfkIE2E6RsWZHfJ0nxOea2VsaCu1bJT9I50pIetgIm+FOaZqu1bnpt8Yq/CeGSPmgS8kz/qChv43/ErQGJ00Iff29yk4W9uz4keZ12S2l22MJXa5B7xWzQ45/z25PpYexOU0bBx8YYajbaNuNMu8u+PSdYO5CmlSqcNG4NAdnziKgIUKsYld3rAV6Xm/Q7rwcZksVjF2AoOeCkSJHjscqV7hNEhzMPZsNyd9fbqKD4tJ7TT7XpXj+iyjuR9eXc64IHbskOCGRSem29o98EWHER+RNn1UsVIUNer+AmR9eYu/1hCdaYSNTwu+0JzS4HEpJzt5BYXuC/+1KudN6kIU+L8gl51ytV+IFpJ9UsZdqYdTC254R2NHAk2ZL5AO6V2yuhUa8AFOMjawLWDMiCStfTjZ8Z8j1t72EhM6/rvcI0XrM1alRV3VMcbkFs0OxgAmAkJBZP3OqQhJIFpKf1IRnezSZ77wWCibbjjICcI+nvRWOX2+R/B1ueaE9qMlQemJMB3CA5pKskqziPbAapPqIPbOf8JgWSOrk0sG/LpRQSrvhsqs5iPkBSLSvJ/w0F9Q==
  template:
    metadata:
      name: velero-credentials
      namespace: default
    type: Opaque
