---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: default
spec:
  encryptedData:
    cloud: AgDIMJ5pyEIuZHM8A+2wHPNXhBLmGdAxkjKe9JpoiRXUaBN+QbQ424juW0wSwfK866WvJoVliH/XMthzTPnhEV89gOvMKnJjAYiQM0d8LKtG2ZJCKMU7kAhEdlhBGQBIcJ9eZa3mJcTIn9FhG4fwJoB7I4PN6YyHjxjKsOLxvoE/Bz8q6gq1FuwtmEFqjqmUCDPg9Zza+WhKWsLV2Dz8scR25KlCXJTSpu7CYudWqk9BR1/puRixMc0H6Clq6yj9MBEaGOZ/QV2V1v0QgIaX+2TXtWayNpZ6Aggj3Sh5eCGeAk0lZ2z0kjwRxQ7movvFEz9YWB3eC0dfGx8xs/wyRauXASnMC+BcZ41i4rkl+PxJICllMMupiFjVnZlKNtTEZmOYEvPZcpkW3A7aow9+fqYBCOfORAWWe59vnAa89Q7QmgEbJYMfTeg4Ggw6cQx8W/inDy8tBDbYCgKvcmUorGdn6kBsAkAIKxFShN19fL9o2waoMOrU1EfU/tlqbPXHCFlBBwSf94xlkjwqhBeroLTqwB4TgkTnZnw6mNC44Sl58lKyavJaHN9FjqAoZO+8EpFj3BxOM93hvKHtLBPeDmsnKA7/wTNTwrZ56vv01ftZcwzLHUByEIaD7bTZmxVeCPrrpY1KcQwuTb3BRfGGhQClPPiR+lk6YTbl9epG3e1wLrKYlLweCiAH1VCrOU+SyxliAkgQSPbXYuNlSI8V73QiZd/HKnZB8A6g4/rQTnvNZFBEQXRU5c+Jo8SgMWjIE8V3C+EjV3IyBzqF/r6+utHWXBC2CZmmFY098wDbqJh7ydWFVLe0/wc175CyWE9Ht+u2QxVXlW5Xbr6hpsDOzolA05zhuLpRNY8L43YUNVa4RYvWM7L/Lk7pk+zx1VmAeTS3DsDVNyQkU0KN
  template:
    metadata:
      name: velero-credentials
      namespace: default
    type: Opaque
