---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: default
spec:
  encryptedData:
    cloud: AgDqf/3qPPZcsYP+N7HxAcnxmIKl+CCN1tjTsvsxc+yn2XDOS2xk4Ipl03VNZVxHjoMAOg6tzfmC3r/PAlEELcCnKspEMyae647uQggGXn7Ub/qFYxm+b2gQb76wLOB2iMXbwAkj7GA4lq6VBYPegTBjCRGSE2Ha5Iek8d4kT/stoKNLkE6i+IHpULV/a/CgRTgfBQfzdHYrJeFjkw+dpuhx6kKSsXlOHTduBfCEX9EgF2wj2BoiLzwYbf3B2L1hRJR+lw+ML4ZJqLeYLEcwpJH9oJAm8k57iWTxR+OerDyP5kfLo9nfEO64medH6p0aIYU8FBP//XyXNnonNBgvKC/d9+qBkc0XRhtVlJ5CvbRKVQo2XDZRJDFdROYCjf3LOzEe7wyPL5QEkLQEW1s1qv2Qpi+al0J6fLj0SaGLJ8/Rh58OyJxeW7MngEKtxlIuYG67+OYH4dSWHpIf6RfHuOr8TuLAhjBi5JtqEGNXzdc73uklbgywLqfYa3jc+3zSmSqR62jy9yIlAUI/Q2+wTBpe/U1RDDXiQ9ofigmGUTp0MFrFWO0X+VoLPZmsjE9fjSmAKUIuHEhx3glQowaHu23JMdcxxJ0wExpZ9SCtSqq/LuBR1HdklpTKI/83ZGlDuyW5ehwkcVOXjBOUIpfTCBnQKVDSBfnTLH/y1Us0b/e2BFy5+M+og1EsiTYxoKTv1kxbJFmNLhfPyBJBTcKUSDznElqoFERC/l7S4PlB0Q9h4spNvjVZgbRLXwkB4iVtqNL8JCHekAFQLTuE0jjeHIbxbznIeg+QKR9IMVbRXgwlxDrYZ2a57ToKsH5PwLf8pxSCWZx9TUv6dnXbelzPeLBMFYYvyN2QJY9ujfuJFsfI8G/qeCkPudp/9n52dWxAxjsoncXfJ7j6VYSyY7RFo6wgpbv67+0B4N+uQuDynxJGcJAdOg/pk0sUWXSasGLtATYpAel+1dfVwxv9elSeaJdKwKl/yRbNBPPM82dKHucY2Uccs+aUbyZJR6HYfuxicTV+wlEFelA4qbJLHDc7T/aYkxcactIs5bwtObMgbVSO6TUd0MijJyXaU3nJRZ2kMVFwKPneHaBhzKOM+afvvcU7qK4XHj9dmNg5gHTA+0BCune/2Q==
  template:
    metadata:
      name: velero-credentials
      namespace: default
    type: Opaque
