name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.setver.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Generate Semantic Version
        id: setver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          version_format: "v${major}.${minor}.${patch}"

      - name: Save version to artifact
        run: echo "${{ steps.setver.outputs.version }}" > version.txt

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt

  build-and-publish-docker:
    needs: version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/arm64
          - linux/amd64
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      
      - name: Download version
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read version
        id: read_version
        run: echo "VERSION=$(cat version.txt)" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.read_version.outputs.VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          platforms: ${{ matrix.platform }}

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: [version, build-and-publish-docker]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Download version
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read version
        id: read_version
        run: echo "VERSION=$(cat version.txt)" >> "$GITHUB_ENV"

      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"${{ steps.read_version.outputs.VERSION }}\"|" deploy/chart/values.yaml

      - name: Commit and tag updated values.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add deploy/chart/values.yaml
          if ! git diff --cached --quiet; then
            git commit -m "chore(chart): update image tag to ${{ steps.read_version.outputs.VERSION }}"
            git tag ${{ steps.read_version.outputs.VERSION }}
            git push origin main
            git push origin ${{ steps.read_version.outputs.VERSION }}
          else
            echo "No changes to commit."
          fi